/* Generated by scripts/fetch-logos.mjs — do not edit by hand.
 * Account logos, keyed by Vitally organization id. Domains were resolved from
 * the email domains of each organization's PostHog users; the marks belong to
 * their owners and are here only to identify the account.
 */
import logo713Online from '../assets/logos/713-online.png'
import logoAmericor from '../assets/logos/americor.png'
import logoApplovinCorp from '../assets/logos/applovin-corp.svg'
import logoAthenaIntelligence from '../assets/logos/athena-intelligence.svg'
import logoAweber from '../assets/logos/aweber.png'
import logoBootDev from '../assets/logos/boot-dev.png'
import logoClineBotInc from '../assets/logos/cline-bot-inc.png'
import logoClinicalNotesAi from '../assets/logos/clinical-notes-ai.png'
import logoCluely from '../assets/logos/cluely.png'
import logoDeterminateSystems from '../assets/logos/determinate-systems.png'
import logoDubclub from '../assets/logos/dubclub.png'
import logoEtacticsInc from '../assets/logos/etactics-inc.png'
import logoGloo from '../assets/logos/gloo.png'
import logoHedra from '../assets/logos/hedra.png'
import logoLahzo from '../assets/logos/lahzo.png'
import logoLayerzero from '../assets/logos/layerzero.png'
import logoLeland from '../assets/logos/leland.png'
import logoMoonshot from '../assets/logos/moonshot.png'
import logoNasuni from '../assets/logos/nasuni.png'
import logoNemoursChildrenSHealth from '../assets/logos/nemours-children-s-health.png'
import logoNowstaInc from '../assets/logos/nowsta-inc.png'
import logoOpenPractice from '../assets/logos/open-practice.webp'
import logoShopgenie from '../assets/logos/shopgenie.png'
import logoSilencerShop from '../assets/logos/silencer-shop.webp'
import logoSmartAccess from '../assets/logos/smart-access.png'
import logoStartengine from '../assets/logos/startengine.svg'
import logoT3ToolsInc from '../assets/logos/t3-tools-inc.png'
import logoTrustlayerInc from '../assets/logos/trustlayer-inc.png'
import logoUsmobile from '../assets/logos/usmobile.svg'
import logoWisprAi from '../assets/logos/wispr-ai.png'
import logoWorksafebc from '../assets/logos/worksafebc.png'

export const ACCOUNT_LOGOS: Record<string, string> = {
  // 713 Online — 713online.com
  '0196873b-4748-0000-cd79-756141922e59': logo713Online,
  // Americor — americor.com
  '019036b2-8681-0000-c33f-a6d7bf5faae2': logoAmericor,
  // AppLovin, Corp — applovin.com
  '01996390-a4fb-0000-7fff-026e7e1f4a85': logoApplovinCorp,
  // Athena Intelligence — athenaintel.com
  '018d3337-0c5f-0000-2e90-62a007a706f4': logoAthenaIntelligence,
  // AWeber — aweber.com
  '018e1ea6-137f-0000-3126-bd5de43d7804': logoAweber,
  // Boot.dev — boot.dev
  '0187e3a5-46d4-0000-ac1f-b71a69e4aa0c': logoBootDev,
  // Cline Bot Inc. — cline.bot
  '01953ee8-325c-0000-49dc-7d9eb290424c': logoClineBotInc,
  // Clinical Notes AI — clinicalnotes.ai
  '0190bd9b-a5d2-0000-9308-230fa32b3043': logoClinicalNotesAi,
  // Cluely — cluely.com
  '0195c9b7-76ce-0000-aa25-952df540c4e1': logoCluely,
  // Determinate Systems — determinate.systems
  '0182b12b-eacc-0000-5204-2bfeb39d5006': logoDeterminateSystems,
  // DubClub — dubclub.win
  '01828424-9e68-0000-ea69-8ae3fd241d9e': logoDubclub,
  // Etactics, Inc. — etactics.com
  '019be25a-f3a9-0000-f28e-9a2cc7a37dfc': logoEtacticsInc,
  // Gloo — gloo.us
  '018c6009-9a44-0000-8c3d-6f7df319589f': logoGloo,
  // Hedra — hedra.com
  '018feb15-20ab-0000-b1f8-a6157b7876d1': logoHedra,
  // Lahzo — lahzo.com
  '01926373-c663-0000-4a1b-14769a84cc81': logoLahzo,
  // LayerZero — layerzerolabs.org
  '019445ee-d0fa-0000-2003-4d34599c010b': logoLayerzero,
  // Leland — joinleland.com
  '0186328e-a414-0000-5380-93e21b1c1bcf': logoLeland,
  // Moonshot — moonshot.money
  '018fa11a-6593-0000-fc53-807b51d0120e': logoMoonshot,
  // Nasuni — nasuni.com
  '01924999-d745-0000-9e8a-6a240806d369': logoNasuni,
  // Nemours Children's Health — nemours.org
  '01939d8e-41f2-0000-5a9c-8011488a9bcd': logoNemoursChildrenSHealth,
  // Nowsta Inc. — nowsta.com
  '0192d900-d620-0000-46a9-f9a712425410': logoNowstaInc,
  // Open Practice — openpractice.net
  '0198a8eb-c178-0000-b015-d688667ed32d': logoOpenPractice,
  // Shopgenie — shopgenie.io
  '01882c43-51fa-0000-4965-5d0a8808b348': logoShopgenie,
  // Silencer Shop — silencershop.com
  '0190b770-0568-0000-6f70-4bfc58c93ebd': logoSilencerShop,
  // Smart Access — smartaccess.io
  '0183668f-132c-0000-95c6-4679eb0ea585': logoSmartAccess,
  // StartEngine — startengine.com
  '01873160-3924-0000-e23d-f96331d15307': logoStartengine,
  // T3 Tools Inc. — ping.gg
  '018a0719-b6b2-0000-1cdd-1dba07e61b1b': logoT3ToolsInc,
  // TrustLayer, Inc. — trustlayer.io
  '019580ae-d173-0000-58ac-c3d15956848e': logoTrustlayerInc,
  // USMobile — usmobile.com
  '019a12ca-58ee-0000-caf8-5dd8ac431cbd': logoUsmobile,
  // Wispr AI — wispr.ai
  '0190165a-4452-0000-5137-e01acf36045f': logoWisprAi,
  // WorkSafeBC — worksafebc.com
  '018a2d6b-b2ec-0000-7c78-3fc459504405': logoWorksafebc
}
